services:
  - type: web
    name: whitefly-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "cicd-whitefly-v2.onrender.com,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://cicd-whitefly-2ee8.vercel.app"
