# Generated by Django 4.1.5 on 2023-01-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=524)),
                ('images', models.FileField(upload_to='whitefly_uploads/')),
            ],
        ),
    ]
